name: pin_bord
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  riverpod: ^2.4.1
  flutter_riverpod: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^7.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.1.0
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
