name: pin_bord
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.9
  path_provider: ^2.0.11
  path: ^1.8.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  auto_route: ^5.0.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^1.7.0
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0

flutter:

  uses-material-design: true
